"""create documents table

Revision ID: 86bfd9158ecb
Revises:
Create Date: 2026-09-11 06:17:08.374064

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86bfd9158ecb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STATUS_VALUES = (
    "uploaded",
    "processing",
    "extracted",
    "needs_review",
    "reviewed",
    "failed",
)

# Created and dropped explicitly: Postgres enum types outlive the table that
# uses them, so an autogenerated `drop_table` alone would leave the type behind
# and the next upgrade would fail with "type document_status already exists".
document_status = sa.Enum(*STATUS_VALUES, name="document_status")


def upgrade() -> None:
    """Create the document_status type and the documents table."""
    document_status.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "documents",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("doc_type", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            # create_type=False: the type is created above, not inline.
            postgresql.ENUM(*STATUS_VALUES, name="document_status", create_type=False),
            server_default="uploaded",
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )


def downgrade() -> None:
    """Drop the documents table and the document_status type."""
    op.drop_table("documents")
    document_status.drop(op.get_bind(), checkfirst=True)
